spring.application.name=kickback
server.port=8080

# database properties
spring.datasource.url=jdbc:mysql://localhost:3306/kickback
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
; spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

app.security.jwt.secret=KickBackSuperSecretKeyForJWT2026Secure
app.security.jwt.expiration-seconds=86400